### ISSUE TITLE
Put the projects under the correct year tab

### ISSUE THREAD

**Issue by Driesvanransbeeck** [HackYourFutureBelgium/bootcamp-site#4]
The projects on https://bootcamp.hackyourfuture.be/projects/ don't appear under the correct year tab. Open Recognition and Stitch are under the 2020 tab and outdoor for all is under the 2019 one.

**Comment by MichielLeyman** [comment]
Thanks Dries. Fixed in https://github.com/HackYourFutureBelgium/bootcamp-site/commit/428c9898f563bd901fb786855ef0baf11ca6de43
